say.lo: /say/code/php-src/ext/say/say.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/say/code/php-src/ext/say $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /say/code/php-src/ext/say/say.c -o say.lo 
$(phplibdir)/say.la: ./say.la
	$(LIBTOOL) --mode=install cp ./say.la $(phplibdir)

./say.la: $(shared_objects_say) $(SAY_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_say) $(SAY_SHARED_LIBADD)

